using UnityEngine;
using UnityEngine.SceneManagement;
using System.Collections.Generic;

public class EnemyAI : MonoBehaviour
{
    public static EnemyAI Instance { get; private set; }

    public enum EnemyCommandState { Defend, Attack, Retreat }

    [Header("Current State")]
    public EnemyCommandState currentEnemyState = EnemyCommandState.Defend;
    public int enemyGold = 200;

    [Header("Chiến thuật (theo tương quan lực lượng)")]
    [Tooltip("Số quân tối thiểu để dám mở tổng tấn công")]
    [SerializeField] private int minAttackForce = 4;
    [Tooltip("Tấn công khi quân ĐỊCH >= quân PLAYER * tỉ lệ này (1 = ngang bằng, <1 = liều hơn)")]
    [SerializeField] private float attackForceRatio = 1f;
    [Tooltip("Đợt tấn công coi như TÀN khi quân còn lại <= lực lượng lúc xuất phát * tỉ lệ này -> co về gom quân")]
    [SerializeField, Range(0f, 1f)] private float pushSpentRatio = 0.4f;
    [Tooltip("Thủ quá lâu (giây) mà đủ quân thì vẫn chủ động đánh (chống rùa)")]
    [SerializeField] private float maxDefendDuration = 45f;

    [Header("Reinforcements Configuration")]
    [Tooltip("Prefab của lính chi viện (nếu không gán sẽ lấy từ Spawner hiện tại)")]
    [SerializeField] private GameObject reinforcementPrefab;
    [Tooltip("Số lượng lính chi viện được spawn")]
    [SerializeField] private int reinforcementCount = 5;

    // Trạng thái theo dõi
    private bool hasCalledReinforcements = false;
    private float defendTimer = 0f;   // thời gian liên tục đang Phòng thủ (chống rùa)
    private int committedForce = 0;   // số quân lúc bắt đầu đợt Tấn công (để biết khi nào push tàn)
    private EnemyBase enemyBase;

    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
            currentEnemyState = EnemyCommandState.Defend;
            Debug.Log("EnemyAI: Khởi tạo Singleton thành công.");
        }
        else
        {
            Destroy(gameObject);
        }
    }

    private void Start()
    {
        // Tự động tìm kiếm EnemyBase trong scene nếu chưa có
        if (enemyBase == null)
        {
            enemyBase = FindFirstObjectByType<EnemyBase>();
        }
    }

    private void OnDestroy()
    {
        if (Instance == this)
        {
            Instance = null;
        }
    }

    /// <summary>
    /// Đăng ký hook để tự sinh EnemyAI cho MỌI scene có EnemyBase.
    /// Lưu ý: [RuntimeInitializeOnLoadMethod] chỉ chạy 1 lần lúc khởi động app, KHÔNG chạy lại khi đổi scene,
    /// nên phải lắng nghe SceneManager.sceneLoaded mới đảm bảo scene trận (load từ menu) cũng có EnemyAI.
    /// </summary>
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
    private static void InstallSceneHook()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
        SceneManager.sceneLoaded += OnSceneLoaded;
        EnsureExistsForActiveScene(); // cho scene đầu tiên
    }

    private static void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        EnsureExistsForActiveScene();
    }

    private static void EnsureExistsForActiveScene()
    {
        if (Instance != null) return;
        if (FindFirstObjectByType<EnemyAI>() != null) return; // đã có sẵn trong scene

        if (FindFirstObjectByType<EnemyBase>() != null)
        {
            GameObject aiObj = new GameObject("EnemyAI_AutoGenerated");
            aiObj.AddComponent<EnemyAI>();
            Debug.Log("EnemyAI: Phát hiện EnemyBase trong scene -> tự động tạo EnemyAI.");
        }
        else
        {
            Debug.LogWarning("EnemyAI: Scene không có EnemyBase -> không tạo EnemyAI.");
        }
    }

    [Header("Debug")]
    [SerializeField] private bool enableDebugLog = true;
    private float debugLogTimer = 0f;

    private void Update()
    {
        float dt = Time.deltaTime;
        UnitFormationManager fm = UnitFormationManager.Instance;
        int enemies = fm != null ? fm.GetEnemyUnitCount() : 0;
        int players = fm != null ? fm.GetPlayerUnitCount() : 0;

        // ===== DEBUG: log mỗi 1 giây =====
        if (enableDebugLog)
        {
            debugLogTimer += dt;
            if (debugLogTimer >= 1f)
            {
                debugLogTimer = 0f;
                Debug.Log($"[EnemyAI] state={currentEnemyState} | enemies={enemies} players={players} " +
                          $"| committed={committedForce} | defendTimer={defendTimer:F0}/{maxDefendDuration}s | FM={(fm != null ? "OK" : "NULL!")}");
                if (fm == null)
                    Debug.LogWarning("[EnemyAI] Thiếu UnitFormationManager trong scene -> không đếm được quân -> AI đứng yên!");
            }
        }

        switch (currentEnemyState)
        {
            case EnemyCommandState.Attack:
                if (enemies == 0 || enemies <= Mathf.CeilToInt(committedForce * pushSpentRatio))
                {
                    // Đợt push đã tàn -> co về gom quân
                    SetDefend($"Đợt tấn công tàn (còn {enemies}/{committedForce}) -> gom quân");
                }
                break;

            case EnemyCommandState.Defend:
            default:
                defendTimer += dt;
                if (enemies >= minAttackForce &&
                    (enemies >= Mathf.CeilToInt(players * attackForceRatio) || defendTimer >= maxDefendDuration))
                {
                    committedForce = enemies;
                    bool byTimeout = !(enemies >= Mathf.CeilToInt(players * attackForceRatio));
                    currentEnemyState = EnemyCommandState.Attack;
                    Debug.Log($"EnemyAI: TẤN CÔNG! (enemy={enemies} vs player={players}" + (byTimeout ? ", do thủ quá lâu" : ", đủ ưu thế") + ")");
                }
                break;
        }

        // Chi viện khi Base địch yếu (giữ nguyên)
        if (enemyBase != null && !hasCalledReinforcements)
        {
            float hpRatio = enemyBase.GetCurrentHealth() / enemyBase.GetMaxHealth();
            if (hpRatio <= 2f / 3f)
            {
                SpawnReinforcements();
            }
        }
    }

    private void SetDefend(string reason)
    {
        currentEnemyState = EnemyCommandState.Defend;
        defendTimer = 0f;
        Debug.Log($"EnemyAI: -> PHÒNG THỦ ({reason}).");
    }

    /// <summary>
    /// Đăng ký EnemyBase vào AI (được gọi từ EnemyBase.Start)
    /// </summary>
    public void RegisterEnemyBase(EnemyBase baseRef)
    {
        enemyBase = baseRef;
    }

    /// <summary>
    /// Đăng ký một mạng quái chết để theo dõi tần suất chết
    /// </summary>
    public void RegisterEnemyDeath()
    {
        // Không còn dùng (đã bỏ trạng thái Rút lui). Giữ hàm để Enemy.EntityDie gọi không lỗi.
    }

    /// <summary>
    /// Cộng tiền sinh vàng cho phe địch
    /// </summary>
    public void AddEnemyGold(int amount)
    {
        enemyGold += amount;
        // Có thể mở rộng để EnemyAI tự động chi tiêu vàng để mua lính ở đây
    }

    /// <summary>
    /// Sinh quân chi viện tại vị trí Spawner
    /// </summary>
    private void SpawnReinforcements()
    {
        hasCalledReinforcements = true;
        Debug.Log("EnemyAI: Máu Base địch xuống dưới 2/3! Triệu hồi CHI VIỆN khẩn cấp!");

        // Tìm tất cả EnemySpawner trong scene để lấy vị trí và prefab quái
        EnemySpawner[] spawners = FindObjectsOfType<EnemySpawner>(true);
        GameObject prefabToSpawn = null;
        Vector3 spawnPos = Vector3.zero;

        if (spawners != null && spawners.Length > 0)
        {
            prefabToSpawn = spawners[0].GetEnemyPrefab();
            spawnPos = spawners[0].transform.position;
        }

        // Fallback 1: Tìm từ WaveManager
        if (prefabToSpawn == null)
        {
            WaveManager waveManager = FindObjectOfType<WaveManager>(true);
            if (waveManager != null && waveManager.mapWaves != null && waveManager.mapWaves.Count > 0)
            {
                Wave firstWave = waveManager.mapWaves[0];
                if (firstWave.enemiesToSpawn != null && firstWave.enemiesToSpawn.Count > 0)
                {
                    prefabToSpawn = firstWave.enemiesToSpawn[0];
                }
                if (waveManager.spawnPoint != null)
                {
                    spawnPos = waveManager.spawnPoint.position;
                }
            }
        }

        // Fallback 2: Tìm bất kỳ quái vật nào (trừ Base) đang hoạt động trong scene làm nguyên mẫu nhân bản
        if (prefabToSpawn == null)
        {
            Enemy[] activeEnemies = FindObjectsOfType<Enemy>(true);
            foreach (Enemy enemy in activeEnemies)
            {
                if (enemy != null && !(enemy is EnemyBase) && !enemy.dead)
                {
                    prefabToSpawn = enemy.gameObject;
                    break;
                }
            }
        }

        // Fallback 3: Lấy cấu hình thủ công trong Inspector
        if (prefabToSpawn == null)
        {
            prefabToSpawn = reinforcementPrefab;
        }

        // Đảm bảo vị trí spawn an toàn (nếu chưa tìm thấy vị trí từ spawner -> spawn tại Base địch)
        if (spawnPos == Vector3.zero && enemyBase != null)
        {
            spawnPos = enemyBase.transform.position + new Vector3(-2f, 0f, 0f); // Spawn lệch sang trái 2 đơn vị
        }

        if (prefabToSpawn == null)
        {
            Debug.LogError("EnemyAI: Không tìm thấy Enemy Prefab để gọi chi viện!");
            return;
        }

        // Sinh quân chi viện
        for (int i = 0; i < reinforcementCount; i++)
        {
            Vector3 pos = spawnPos + new Vector3(0f, i * 0.3f, 0f);
            GameObject spawnedUnit = Instantiate(prefabToSpawn, pos, Quaternion.identity);
            
            // Nếu prefab là đối tượng trong scene hoạt động, cần kích hoạt nó hoạt động lại (phòng hờ)
            if (!spawnedUnit.activeSelf)
            {
                spawnedUnit.SetActive(true);
            }
            
            Debug.Log($"EnemyAI: Đã spawn lính chi viện #{i + 1} tại {pos}");
        }

        Debug.Log($"EnemyAI: Đã triệu hồi thành công {reinforcementCount} quân địch để tạm thời áp đảo người chơi!");
    }
}
