using UnityEngine;
using System.Collections.Generic;

public class EnemyAI : MonoBehaviour
{
    public static EnemyAI Instance { get; private set; }

    public enum EnemyCommandState { Defend, Attack, Retreat }

    [Header("Current State")]
    public EnemyCommandState currentEnemyState = EnemyCommandState.Defend;
    public int enemyGold = 200;

    [Header("Tactical Parameters")]
    [Tooltip("Thời gian chờ trước khi ép phe địch tấn công nếu người chơi không động tĩnh gì (giây)")]
    [SerializeField] private float timeBeforeForceAttack = 180f; // 3 phút
    [Tooltip("Số lượng lính người chơi tối thiểu để kích hoạt địch rút lui")]
    [SerializeField] private int playerTroopThresholdForRetreat = 6;
    [Tooltip("Khoảng thời gian (giây) để đếm mạng quái bị tiêu diệt")]
    [SerializeField] private float deathRateTimeWindow = 10f;
    [Tooltip("Số mạng quái bị tiêu diệt tối thiểu trong cửa sổ thời gian để kích hoạt rút lui")]
    [SerializeField] private int deathRateThresholdForRetreat = 3;
    [Tooltip("Thời gian quái rút lui trước khi quay lại trạng thái phòng thủ (giây)")]
    [SerializeField] private float retreatDuration = 15f;

    [Header("Reinforcements Configuration")]
    [Tooltip("Prefab của lính chi viện (nếu không gán sẽ lấy từ Spawner hiện tại)")]
    [SerializeField] private GameObject reinforcementPrefab;
    [Tooltip("Số lượng lính chi viện được spawn")]
    [SerializeField] private int reinforcementCount = 5;

    // Trạng thái theo dõi
    private float timeSinceLevelStart = 0f;
    private bool hasPlayerAttacked = false;
    private bool hasCalledReinforcements = false;
    private float retreatTimer = 0f;
    private List<float> enemyDeathTimes = new List<float>();
    private EnemyBase enemyBase;

    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
            currentEnemyState = EnemyCommandState.Defend;
            Debug.Log("EnemyAI: Khởi tạo Singleton thành công.");
        }
        else
        {
            Destroy(gameObject);
        }
    }

    private void Start()
    {
        // Tự động tìm kiếm EnemyBase trong scene nếu chưa có
        if (enemyBase == null)
        {
            enemyBase = FindObjectOfType<EnemyBase>();
        }
    }

    private void OnDestroy()
    {
        if (Instance == this)
        {
            Instance = null;
        }
    }

    /// <summary>
    /// Tự động sinh EnemyAI GameObject trong màn chơi mà không cần kéo thả tay.
    /// </summary>
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
    private static void AutoInitialize()
    {
        // Nếu người dùng đã tự tay kéo thả hoặc tạo sẵn EnemyAI trong scene -> KHÔNG tự động tạo GameObject mới nữa
        if (FindObjectOfType<EnemyAI>() != null)
        {
            Debug.Log("EnemyAI: Đã tìm thấy EnemyAI được cấu hình sẵn trong scene. Bỏ qua tự động khởi tạo.");
            return;
        }

        if (FindObjectOfType<EnemyBase>() != null)
        {
            if (Instance == null)
            {
                GameObject aiObj = new GameObject("EnemyAI_AutoGenerated");
                aiObj.AddComponent<EnemyAI>();
                Debug.Log("EnemyAI: Phát hiện thấy EnemyBase trong scene, tự động khởi chạy EnemyAI!");
            }
        }
    }

    private void Update()
    {
        timeSinceLevelStart += Time.deltaTime;

        // 1. Kiểm tra xem người chơi đã từng ra lệnh Tấn công chưa
        if (!hasPlayerAttacked && GameCommander.currentState == GameCommander.CommandState.Attack)
        {
            hasPlayerAttacked = true;
            Debug.Log("EnemyAI: Phát hiện người chơi đã chủ động TẤN CÔNG.");
        }

        // 2. Nếu sau 3 phút người chơi vẫn bất động -> Địch chủ động TẤN CÔNG
        if (!hasPlayerAttacked && timeSinceLevelStart >= timeBeforeForceAttack && currentEnemyState == EnemyCommandState.Defend)
        {
            currentEnemyState = EnemyCommandState.Attack;
            Debug.Log($"EnemyAI: Đã qua {timeBeforeForceAttack} giây mà người chơi không tấn công. Ra lệnh quân địch: TẤN CÔNG!");
        }

        // 3. Quản lý trạng thái RÚT LUI (Retreat)
        if (currentEnemyState == EnemyCommandState.Retreat)
        {
            retreatTimer -= Time.deltaTime;
            if (retreatTimer <= 0f)
            {
                // Hết thời gian rút lui -> Quay về phòng thủ để củng cố lực lượng
                currentEnemyState = EnemyCommandState.Defend;
                Debug.Log("EnemyAI: Hết thời gian rút lui. Toàn quân địch quay lại trạng thái PHÒNG THỦ!");
            }
        }
        else
        {
            // Kiểm tra các điều kiện để kích hoạt RÚT LUI
            // Dọn dẹp danh sách thời điểm chết quá hạn
            enemyDeathTimes.RemoveAll(t => Time.time - t > deathRateTimeWindow);

            int playerTroopCount = UnitFormationManager.Instance != null ? UnitFormationManager.Instance.GetPlayerUnitCount() : 0;
            bool playerCrowded = playerTroopCount >= playerTroopThresholdForRetreat;
            bool highDeaths = enemyDeathTimes.Count >= deathRateThresholdForRetreat;

            if (playerCrowded || highDeaths)
            {
                currentEnemyState = EnemyCommandState.Retreat;
                retreatTimer = retreatDuration;
                Debug.Log($"EnemyAI: Phát hiện sức tấn công phe Player quá mạnh! (Lính đông: {playerCrowded} - {playerTroopCount} quân, Chết liên tục: {highDeaths} - {enemyDeathTimes.Count} lính). Ra lệnh quân địch: RÚT LUI!");
            }
        }

        // 4. Kiểm tra lượng máu của EnemyBase để gọi chi viện
        if (enemyBase != null && !hasCalledReinforcements)
        {
            float hpRatio = enemyBase.GetCurrentHealth() / enemyBase.GetMaxHealth();
            if (hpRatio <= 2f / 3f)
            {
                SpawnReinforcements();
            }
        }
    }

    /// <summary>
    /// Đăng ký EnemyBase vào AI (được gọi từ EnemyBase.Start)
    /// </summary>
    public void RegisterEnemyBase(EnemyBase baseRef)
    {
        enemyBase = baseRef;
    }

    /// <summary>
    /// Đăng ký một mạng quái chết để theo dõi tần suất chết
    /// </summary>
    public void RegisterEnemyDeath()
    {
        enemyDeathTimes.Add(Time.time);
    }

    /// <summary>
    /// Cộng tiền sinh vàng cho phe địch
    /// </summary>
    public void AddEnemyGold(int amount)
    {
        enemyGold += amount;
        // Có thể mở rộng để EnemyAI tự động chi tiêu vàng để mua lính ở đây
    }

    /// <summary>
    /// Sinh quân chi viện tại vị trí Spawner
    /// </summary>
    private void SpawnReinforcements()
    {
        hasCalledReinforcements = true;
        Debug.Log("EnemyAI: Máu Base địch xuống dưới 2/3! Triệu hồi CHI VIỆN khẩn cấp!");

        // Tìm tất cả EnemySpawner trong scene để lấy vị trí và prefab quái
        EnemySpawner[] spawners = FindObjectsOfType<EnemySpawner>(true);
        GameObject prefabToSpawn = null;
        Vector3 spawnPos = Vector3.zero;

        if (spawners != null && spawners.Length > 0)
        {
            prefabToSpawn = spawners[0].GetEnemyPrefab();
            spawnPos = spawners[0].transform.position;
        }

        // Fallback 1: Tìm từ WaveManager
        if (prefabToSpawn == null)
        {
            WaveManager waveManager = FindObjectOfType<WaveManager>(true);
            if (waveManager != null && waveManager.mapWaves != null && waveManager.mapWaves.Count > 0)
            {
                Wave firstWave = waveManager.mapWaves[0];
                if (firstWave.enemiesToSpawn != null && firstWave.enemiesToSpawn.Count > 0)
                {
                    prefabToSpawn = firstWave.enemiesToSpawn[0];
                }
                if (waveManager.spawnPoint != null)
                {
                    spawnPos = waveManager.spawnPoint.position;
                }
            }
        }

        // Fallback 2: Tìm bất kỳ quái vật nào (trừ Base) đang hoạt động trong scene làm nguyên mẫu nhân bản
        if (prefabToSpawn == null)
        {
            Enemy[] activeEnemies = FindObjectsOfType<Enemy>(true);
            foreach (Enemy enemy in activeEnemies)
            {
                if (enemy != null && !(enemy is EnemyBase) && !enemy.dead)
                {
                    prefabToSpawn = enemy.gameObject;
                    break;
                }
            }
        }

        // Fallback 3: Lấy cấu hình thủ công trong Inspector
        if (prefabToSpawn == null)
        {
            prefabToSpawn = reinforcementPrefab;
        }

        // Đảm bảo vị trí spawn an toàn (nếu chưa tìm thấy vị trí từ spawner -> spawn tại Base địch)
        if (spawnPos == Vector3.zero && enemyBase != null)
        {
            spawnPos = enemyBase.transform.position + new Vector3(-2f, 0f, 0f); // Spawn lệch sang trái 2 đơn vị
        }

        if (prefabToSpawn == null)
        {
            Debug.LogError("EnemyAI: Không tìm thấy Enemy Prefab để gọi chi viện!");
            return;
        }

        // Sinh quân chi viện
        for (int i = 0; i < reinforcementCount; i++)
        {
            Vector3 pos = spawnPos + new Vector3(0f, i * 0.3f, 0f);
            GameObject spawnedUnit = Instantiate(prefabToSpawn, pos, Quaternion.identity);
            
            // Nếu prefab là đối tượng trong scene hoạt động, cần kích hoạt nó hoạt động lại (phòng hờ)
            if (!spawnedUnit.activeSelf)
            {
                spawnedUnit.SetActive(true);
            }
            
            Debug.Log($"EnemyAI: Đã spawn lính chi viện #{i + 1} tại {pos}");
        }

        Debug.Log($"EnemyAI: Đã triệu hồi thành công {reinforcementCount} quân địch để tạm thời áp đảo người chơi!");
    }
}
